apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rmiserver-deployment
spec:
  selector:
    matchLabels:
      app: rmiserver
  replicas: 3 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: rmiserver
    spec:
      containers:
      - name: rmiserver
        image: docker.io/gbsnaker/rmiserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1099
